project: 
  type: website
  output-dir: docs
  render:
    - "*.*"
    - "!itutorials/*_Harmony.ipynb"
    - "!qtutorials/*_Harmony.qmd"
    - "!qtutorials/Earthdata_*"
    - "!qtutorials/earthdatalogin_sst.qmd"

execute:
  freeze: auto
  
website:
  page-navigation: true  
  title: "NOAA Fisheries Hackdays"
  favicon: "images/favicon-16x16.png"
  site-url: https://nmfs-opensci.github.io/NOAAHackDays
  repo-url: https://github.com/nmfs-opensci/NOAAHackDays
  repo-actions: [edit, issue, source]
  
  page-footer: <img src="https://github.com/nmfs-opensci/assets/blob/main/logo/nmfs-opensci-logo2.png?raw=true" alt="NMFS Open Science logo" style="width:150px"><br />NMFS Open Science (2023)
 
  sidebar:
    logo: https://github.com/nmfs-opensci/assets/blob/main/logo/nmfs-opensci-logo2.png?raw=true
    pinned: true
    align: center
    
    style: "docked"
    collapse-level: 1
    toc-expand: false
    contents:
      - text: "Welcome"
        href: index.md
      - text: "Prerequisites"
        href: prerequisites.md 
      - text: "About"
        href: about.md
#      - text: "Slides"
#        href: slides.md
      - section: "R Tutorials"
        contents: 
          - text: "NASA Earth Data Access"
            href: qtutorials/earthdataaccess.qmd
          - text: "Historical red-lining and tree cover in SF"
            href: qtutorials/Introduction_to_Cloud_R.qmd
      - section: "Python Tutorials"
        contents: 
          - text: "Introduction"
            href: itutorials/Introduction_to_Cloud_Python.ipynb
          - text: "Earthdata Search"
            href: itutorials/Earthdata_Search_Discovery_earthaccess.ipynb
          - text: "Access, Subset & Plot"
            href: itutorials/Earthdata_Subset_and_Plot.ipynb
  navbar:
    background: primary
    search: true
    right: 
      - icon: server
        href: https://dhub.opensci.live/
        text: "JupyterHub"
      - icon: wechat
        href: https://github.com/nmfs-opensci/NOAAHackDays/discussions
        text: "Discussions"
#      - icon: slack
#        href: https://app.slack.com/client/T05PV2USY56/C05P7QP47UL
#        text: "Slack"
      - icon: github
        href: https://github.com/nmfs-opensci/NOAAHackDays
        text: "repo"
      - icon: globe
        href: https://github.com/nmfs-opensci
        text: "GH org"
        
format:
  html:
    theme:
      light: cosmo
      dark: [cosmo, theme-dark.scss]
    code-background: true
    code-copy: true
    css: styles.css
    toc: true
    toc-depth: 2
    include-before-body: translate.html

#filters:
#  - include-files.lua
#  - quarto
