project: 
  type: website
  output-dir: docs
  render:
    - "*.*"
    - "!nasa-tutorials/*.ipynb"

execute:
  freeze: auto
  
website:
  page-navigation: true  
  title: "Hack Day Dec 19"
  favicon: "images/favicon-16x16.png"
  site-url: https://nmfs-opensci.github.io/NOAAHackDay-Dec-2023
  repo-url: https://github.com/nmfs-opensci/NOAAHackDay-Dec-2023
  repo-actions: [edit, issue, source]
  
  page-footer: <img src="https://github.com/nmfs-opensci/assets/blob/main/logo/nmfs-opensci-logo2.png?raw=true" alt="NMFS Open Science logo" style="width:150px"><br />NMFS Open Science (2023)
 
  sidebar:
    logo: https://github.com/nmfs-opensci/assets/blob/main/logo/nmfs-opensci-logo2.png?raw=true
    pinned: true
    align: center
    
    style: "docked"
    collapse-level: 1
    toc-expand: false
    contents:
      - text: "Welcome"
        href: index.md
      - text: "Prerequisites"
        href: prerequisites.md 
      - text: "Schedule"
        href: schedule.md
      - text: "Slides"
        href: slides.md
      - section: "Tutorials"
        contents: 
          - text: "Search & Discovery"
            href: tutorials/Earthdata_Search_Discovery_earthaccess.ipynb
          - text: "Access, Subset & Plot"
            href: tutorials/Earthdata_Subset_and_Plot.ipynb

format:
  html:
    theme:
      light: cosmo
      dark: [cosmo, theme-dark.scss]
    code-background: true
    code-copy: true
    css: styles.css
    toc: true
    toc-depth: 2
    include-before-body: translate.html

#filters:
#  - include-files.lua
#  - quarto
